name: motor_temp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.16.4
  - alsa-lib=1.2.14
  - anyio=4.10.0
  - aom=3.6.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.3
  - contourpy=1.3.2
  - cpuonly=2.0
  - cpython=3.10.18
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - fqdn=1.5.1
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.14
  - greenlet=3.2.4
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.4.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=7.4.9
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.2.2
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - mako=1.3.10
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mistune=3.1.4
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - narwhals=2.2.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.4.2
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numpy=2.2.6
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - optuna=4.5.0
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.0
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - plotly=6.3.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=24.0.1
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlalchemy=2.0.43
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=1.4.1
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - astor==0.8.1
      - cloudpickle==3.1.1
      - filelock==3.11.0
      - fsspec==2025.7.0
      - json-tricks==3.17.3
      - nni==3.0
      - nvidia-ml-py==13.580.65
      - prettytable==3.16.0
      - pythonwebhdfs==0.2.3
      - responses==0.25.8
      - schema==0.7.7
      - simplejson==3.20.1
      - sympy==1.13.1
      - typeguard==4.1.2
      - websockets==15.0.1
prefix: /home/dmayal/miniconda3/envs/motor_temp
